### ISSUE TITLE
"Fast" simulation parameters cause instability

### ISSUE THREAD

**Issue by mintar** [DFKI-NI/pbr_tools#4]
The new "fast" simulation parameters (specifically, `max_step_size = 0.003`) cause instability while picking up the power drill. This is with the ["Berghofstraße / Moelk" demo](https://github.com/DFKI-NI/mobipick#pick--place-with-move_base-demo-berghoffstra%C3%9Fe).

#### with "slow" physics parameters (`max_step_size = 0.001`)

https://github.com/DFKI-NI/pbr_tools/assets/320188/8084ad2e-c0ef-484e-9c34-b0aae52fdeb3

#### with "fast" physics parameters (`max_step_size = 0.003`)

https://github.com/DFKI-NI/pbr_tools/assets/320188/4f8c3c63-54ab-46b6-808b-e9febc16176c

This effect is reproducible and happens every time.

**Comment by mintar** [comment]
@oscar-lima, @jarkenau : Any ideas (except changing the `max_step_size` back to 0.001)?

**Comment by mintar** [comment]
I already tried playing around with the `iters`, `sor`, `cfm` and `contact_surface_layer` parameters, but nothing seems to work except reducing the `max_step_size` again.

**Comment by oscar-lima** [comment]
> @oscar-lima, @jarkenau : Any ideas (except changing the `max_step_size` back to 0.001)?

I fixed the issue! see: https://github.com/DFKI-NI/mobipick/pull/15
